[[plugins]]
package = "netlify-plugin-minify-html"

  [plugins.inputs]
  removeComments = true
  collapseWhitespace = true
  minifyCSS = true
  minifyJS = true

[build]
command = "pnpm run build:css"
publish = "public"
